services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-management-sqldb
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "TuPassword123$"
      ACCEPT_EULA: "Y" 
    volumes:
      - sqldata:/var/opt/mssql 

  webapi:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: task-management-webapi
    ports:
      - "8080:8080" 
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqldb;Database=TaskManagementDb;User Id=sa;Password=TuPassword123$;Encrypt=False;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://+:8080" 
      ASPNETCORE_ENVIRONMENT: "Development" 
    depends_on:
        - sqldb
volumes:
  sqldata: 